wip: test writing documentation
ProgressiveCoders/Spoke pull request #1380
Opened 2020-01-23 17:05 UTC by schuyler1d

# Fixes no full documentation on how to write tests

## Description

Let's document testing patterns, gotchas and best practices.

- [ ] Figure out when we really need mount() vs. shallow() in React components
- [ ] put a `sleep` in ./lib or somewhere else appropriate (and document)

and generally need more details.  This outline is meant to be fleshed out -- please help expand!

- [x] My PR is labeled [WIP] if it is in progress

2020-01-28 18:53 UTC, ibrand commented
This is so helpful!! I can try and help add stuff on too. Do you think we could merge it as is but included that we need more contributions to it? Just to make folks are actually able to find what's already here?

2021-03-05 15:49 UTC, Frydafly commented
Does this cover this issue? https://github.com/MoveOnOrg/Spoke/issues/410

2021-03-05 15:54 UTC, schuyler1d commented
> Does this cover this issue? #410

No -- worker processes are background 'cron' jobs -- this is for how to run tests, which we would need to update, if we merged this -- e.g. we should at least link to Cypress test documentation I believe we have.

2021-03-10 18:53 UTC, Frydafly commented
@schuyler1d is this the documentation you're referring to? https://github.com/MoveOnOrg/Spoke/blob/ddd32f474461da98d6377b59e8a2f76099370543/docs/HOWTO-run_tests.md#integration-testing

2021-03-18 20:17 UTC, Frydafly commented
hey @schuyler1d wondering if you might want to add this as a change to this existing document? https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-run_tests.md

2021-03-18 20:37 UTC, schuyler1d commented
I think we were thinking of it as a separate document just to separate the 'I made a change and want to run the tests' vs. 'I am writing a test' which is more a subset of code guidelines.  But agree that either way it would work -- it's more the task of completing this document (and then putting it somewhere)

2021-03-20 13:52 UTC, Frydafly commented
hm! in that case @schuyler1d do you think it would be beneficial to merge as-is, perhaps with a caveat text at the bottom that this document could use more work, so that there is more visibility on this doc and folks might be inspired to add to it? @schuyler1d

2021-04-23 15:54 UTC, Frydafly commented
@schuyler1d I think it would be great to merge as-is and get folks adding to this/contributing more! what do you think?

2021-04-23 15:55 UTC, Frydafly approved these changes
🥳 -- actually, @schuyler1d would be great to add this doc to the sidebar so that this shows up on the microsite, maybe even under the help-needed section!

2021-04-23 15:58 UTC, Frydafly requested changes
Can you add this doc to the [sidebar.md file](_sidebar.md) and then we can merge?

2026-05-05 18:55 UTC, closed without merging